apiVersion: v1
kind: Service
metadata:
  name: purchase-agent-service
  namespace: part-a-purchase-ns
spec:
  selector:
    app: purchase-agent
  ports:
  - port: 80
    targetPort: 10001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cement-agent-service
  namespace: part-a-cement-ns
spec:
  selector:
    app: cement-agent
  ports:
  - port: 80
    targetPort: 10002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: steel-agent-service
  namespace: part-a-steel-ns
spec:
  selector:
    app: steel-agent
  ports:
  - port: 80
    targetPort: 10003
  type: ClusterIP