apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-endpoints
  namespace: part-a-purchase-ns
data:
  purchase-endpoint: "PURCHASE_ALB_ENDPOINT"
  cement-endpoint: "CEMENT_ALB_ENDPOINT"
  steel-endpoint: "STEEL_ALB_ENDPOINT"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-endpoints
  namespace: part-a-cement-ns
data:
  purchase-endpoint: "PURCHASE_ALB_ENDPOINT"
  cement-endpoint: "CEMENT_ALB_ENDPOINT"
  steel-endpoint: "STEEL_ALB_ENDPOINT"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-endpoints
  namespace: part-a-steel-ns
data:
  purchase-endpoint: "PURCHASE_ALB_ENDPOINT"
  cement-endpoint: "CEMENT_ALB_ENDPOINT"
  steel-endpoint: "STEEL_ALB_ENDPOINT"