apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-endpoints
  namespace: part-a-purchase-ns
data:
  purchase-endpoint: "ALB_DNS_NAME/purchase"
  cement-endpoint: "ALB_DNS_NAME/cement"
  steel-endpoint: "ALB_DNS_NAME/steel"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-endpoints
  namespace: part-a-cement-ns
data:
  purchase-endpoint: "ALB_DNS_NAME/purchase"
  cement-endpoint: "ALB_DNS_NAME/cement"
  steel-endpoint: "ALB_DNS_NAME/steel"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-endpoints
  namespace: part-a-steel-ns
data:
  purchase-endpoint: "ALB_DNS_NAME/purchase"
  cement-endpoint: "ALB_DNS_NAME/cement"
  steel-endpoint: "ALB_DNS_NAME/steel"