apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: purchase-agent-hpa
  namespace: part-a-purchase-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: purchase-agent
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cement-agent-hpa
  namespace: part-a-cement-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cement-agent
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: steel-agent-hpa
  namespace: part-a-steel-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: steel-agent
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80